---
title: "Faasm latency measurements - wiki4M dataset"
author: "Jakub Szewczyk"
date: "15-09-2021"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(rio)
library(scales)
library(xtable)
knitr::opts_chunk$set(echo = FALSE)
```

```{r read_csv, include=FALSE, cache=TRUE, cache.extra = file.info("wtable.csv")}
raw_csv <- import('subtable.csv')

t_data <- raw_csv %>%
  mutate (
    opts_host = factor(opts_host),
    opts_user = factor(opts_user),
    opts_function = factor(opts_function),
    opts_ndp = factor(opts_ndp, levels = c(0, 0.25, 0.5, 0.75, 1, 1.25), labels = c("0%", "25%", "50%", "75%", "100%", "AoS")),
    total_requests = (errors_count + results_count),
    error_rate = errors_count / (errors_count + results_count),
    # Work around bad outlier removal, use q3+1.5*IQR as an estimate of max non-outlier value
    latency_us_q99pct = pmin(latency_us_q99pct, latency_us_q3 + 1.5*(latency_us_q3 - latency_us_q1)),
    rps_offset = abs(avg_rps_avg_rps - opts_req_rps) / opts_req_rps
   )
function_name <- toString(first(t_data$opts_function))

usms <- 1.0/1000.0
uss <- usms/1000.0

paper_plot_w <- 4
paper_plot_h <- 2.25
paper_font <- "serif"
paper_pointsize <- 10
paper_theme <- theme_minimal() +
  theme(
    plot.title=element_blank(),
    legend.margin=margin(0,0,0,0,"cm")
  )
set1_scale <- brewer_pal(palette="Set1")(7)
set1_scale[6] = set1_scale[7]
paper_disc_scale <- scale_color_manual(values = set1_scale)
paper_fill_scale <- scale_fill_manual(values = set1_scale)
paper_shape_scale <- scale_shape(solid = FALSE)

paper_plot_path <- paste0('plots/', function_name, '_')
```

## Latencies

```{r latency_rps_median}
# ymin = latency_us_q1*plot_scale, , ymax = latency_us_q3*plot_scale
gplt <- ggplot(t_data %>% filter(rps_offset < 0.05),
    aes(x = opts_req_rps, group = opts_ndp, color = opts_ndp)) +
  paper_disc_scale + paper_fill_scale + paper_shape_scale + paper_theme +
  geom_line(aes(y = latency_us_med*uss)) +
  geom_point(aes(y = latency_us_med*uss, shape = opts_ndp)) +
  scale_x_log10(breaks = log_breaks(n=10), label = scales::label_comma(accuracy = 10)) +
  scale_y_log10(breaks = log_breaks(n=10), label = scales::label_comma(accuracy = 0.01), expand = c(0.01,0)) +
  labs(title = "Latency for a given request per second rate", color = "% NDP", shape = "% NDP") +
  xlab("Throughput [requests/second]") + ylab("Median latency [s]")

pdf(paste0(paper_plot_path, "latency_rps_median.pdf"), width=paper_plot_w, height=paper_plot_h, useDingbats = FALSE, family = paper_font, pointsize = paper_pointsize)
plot(gplt)
dev.off()
gplt
```

```{r latency_rps_unloaded_boxplot}
gplt <- ggplot(t_data %>% filter(opts_req_rps == 20),
    aes(y = opts_ndp, color = opts_ndp)) +
  paper_disc_scale + paper_fill_scale + paper_shape_scale + paper_theme +
  geom_boxplot(stat="identity", aes(
    xmin = latency_us_q1pct*usms, xmax = usms*latency_us_q99pct,
    xlower = latency_us_q1*usms, xupper = latency_us_q3*usms,
    xmiddle = latency_us_med*usms)) +
  guides(color = "none") +
  ylab("% Offloaded") + xlab("Latency [ms]")

pdf(paste0(paper_plot_path, "latency_rps_unloaded_boxplot.pdf"), width=paper_plot_w, height=paper_plot_h*0.4, useDingbats = FALSE, family = paper_font, pointsize = paper_pointsize)
plot(gplt)
dev.off()

lat_table <- t_data %>% filter(opts_req_rps == 20) %>%
  select(opts_ndp,
    latency_us_q1pct, latency_us_q99pct,
    latency_us_q1, latency_us_q3,
    latency_us_med
  )
lat_table <- column_to_rownames(lat_table, var="opts_ndp")
print(file=paste0(paper_plot_path, "latency_rps_unloaded_table.tex"), xtable(lat_table),floating=FALSE,latex.environments=NULL,booktabs=TRUE)

gplt
```

```{r boxplot_v}
gplt <- ggplot(t_data %>% filter(opts_req_rps == 20),
    aes(x = opts_ndp, color = opts_ndp)) +
  paper_disc_scale + paper_fill_scale + paper_shape_scale + paper_theme +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  geom_boxplot(stat="identity", aes(
    ymin = latency_us_q1pct*usms, ymax = usms*latency_us_q99pct,
    lower = latency_us_q1*usms, upper = latency_us_q3*usms,
    middle = latency_us_med*usms)) +
  guides(color = "none") +
  xlab("% Offloaded") + ylab("Latency [ms]")

pdf(paste0(paper_plot_path, "latency_rps_unloaded_boxplot_v.pdf"), width=paper_plot_w*0.4, height=paper_plot_h, useDingbats = FALSE, family = paper_font, pointsize = paper_pointsize)
plot(gplt)
dev.off()
gplt
```

```{r plot_error_rate}
gplt <- ggplot(t_data, aes(x = opts_req_rps, y = error_rate * 100.0, group = opts_ndp, color = opts_ndp)) +
  coord_cartesian(ylim=c(0, 70), xlim=c(0, max(t_data$opts_req_rps))) +
  geom_point(aes(shape = opts_ndp)) +
  geom_line() +
  paper_disc_scale + paper_fill_scale + paper_shape_scale + paper_theme +
  labs(title = "Error rate", color = "% NDP", shape = "% NDP") +
  ylab("Error %") + xlab("Requests/s")

pdf(paste0(paper_plot_path, "error_rate.pdf"), width=paper_plot_w, height=paper_plot_h, useDingbats = FALSE, family = paper_font, pointsize = paper_pointsize)
plot(gplt)
dev.off()
gplt
```

```{r table_network}
net_table <- t_data %>% filter(opts_req_rps <= 200) %>% filter(opts_req_rps >= 30) %>%
  group_by(opts_ndp) %>%
  summarise(mean = mean((monitor_computenet_tx_bytes_sum + monitor_storagenet_tx_bytes_sum) / results_count))
net_table <- column_to_rownames(net_table, var="opts_ndp")
print(file=paste0(paper_plot_path, "network_table.tex"), xtable(net_table),floating=FALSE,latex.environments=NULL,booktabs=TRUE)

ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = (monitor_computenet_tx_bytes_sum + monitor_storagenet_tx_bytes_sum) / results_count, group = opts_ndp, color = opts_ndp)) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1), expand = c(0.01, 0.01)) +
  scale_y_continuous(trans = 'identity', expand = c(0.1,0), limits = c(0, NA), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Total bytes per request sent over network") +
  xlab("Req/s") + ylab("bytes/request")
```

```{r cpums_load}
gplt <- ggplot(t_data,
    aes(x = opts_req_rps, group = opts_ndp, color = opts_ndp)) +
  coord_cartesian(ylim = c(0, 100)) +
  paper_disc_scale + paper_fill_scale + paper_shape_scale + paper_theme +
  geom_line(aes(linetype="Compute", y = 100.0*(monitor_computecpums_user_sum + monitor_computecpums_nice_sum + monitor_computecpums_system_sum + monitor_computecpums_irq_sum + monitor_computecpums_softirq_sum)/(monitor_computecpums_user_sum + monitor_computecpums_nice_sum + monitor_computecpums_system_sum + monitor_computecpums_idle_sum + monitor_computecpums_iowait_sum + monitor_computecpums_irq_sum + monitor_computecpums_softirq_sum))) +
  geom_point(aes(shape=opts_ndp, y = 100.0*(monitor_computecpums_user_sum + monitor_computecpums_nice_sum + monitor_computecpums_system_sum + monitor_computecpums_irq_sum + monitor_computecpums_softirq_sum)/(monitor_computecpums_user_sum + monitor_computecpums_nice_sum + monitor_computecpums_system_sum + monitor_computecpums_idle_sum + monitor_computecpums_iowait_sum + monitor_computecpums_irq_sum + monitor_computecpums_softirq_sum))) +
  geom_line(aes(linetype="Storage", y = 100.0*(monitor_storagecpums_user_sum + monitor_storagecpums_nice_sum + monitor_storagecpums_system_sum + monitor_storagecpums_irq_sum + monitor_storagecpums_softirq_sum)/(monitor_storagecpums_user_sum + monitor_storagecpums_nice_sum + monitor_storagecpums_system_sum + monitor_storagecpums_idle_sum + monitor_storagecpums_iowait_sum + monitor_storagecpums_irq_sum + monitor_storagecpums_softirq_sum))) +
  geom_point(aes(shape=opts_ndp, y = 100.0*(monitor_storagecpums_user_sum + monitor_storagecpums_nice_sum + monitor_storagecpums_system_sum + monitor_storagecpums_irq_sum + monitor_storagecpums_softirq_sum)/(monitor_storagecpums_user_sum + monitor_storagecpums_nice_sum + monitor_storagecpums_system_sum + monitor_storagecpums_idle_sum + monitor_storagecpums_iowait_sum + monitor_storagecpums_irq_sum + monitor_storagecpums_softirq_sum))) +
  scale_x_log10(breaks = log_breaks(n=10), label = scales::label_comma(accuracy = 0.1)) +
  scale_y_continuous(breaks = pretty_breaks(n=10), label = scales::label_comma(accuracy = 1)) +
  labs(title = "CPU load", color = "% NDP", shape = "% NDP", linetype = "Node") +
  xlab("Throughput [requests/second]") + ylab("Cpu usage (%)")

pdf(paste0(paper_plot_path, "cpu_load.pdf"), width=paper_plot_w, height=paper_plot_h, useDingbats = FALSE, family = paper_font, pointsize = paper_pointsize)
plot(gplt)
dev.off()
gplt
```

```{r plot_cpu_load}
ggplot(t_data) +
  paper_disc_scale + paper_fill_scale + paper_shape_scale + paper_theme +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_computeprocs_running_avg, group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_storageprocs_running_avg, group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'identity', breaks = breaks_pretty(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = breaks_pretty(n=12)) +
  labs(title = "Average RUNNING threads") +
  xlab("Req/s") + ylab("count")
```

```{r total_utilization}
gplt <- ggplot(t_data %>% filter(rps_offset < 0.05),
    aes(x = opts_req_rps, group = opts_ndp, color = opts_ndp)) +
  coord_cartesian(ylim = c(0, 100)) +
  paper_disc_scale + paper_fill_scale + paper_shape_scale + paper_theme +
  geom_line(aes(y = 50.0*(monitor_storagecpums_user_sum + monitor_storagecpums_nice_sum + monitor_storagecpums_system_sum + monitor_storagecpums_irq_sum + monitor_storagecpums_softirq_sum)/(monitor_storagecpums_user_sum + monitor_storagecpums_nice_sum + monitor_storagecpums_system_sum + monitor_storagecpums_idle_sum + monitor_storagecpums_iowait_sum + monitor_storagecpums_irq_sum + monitor_storagecpums_softirq_sum) + 50.0*(monitor_computecpums_user_sum + monitor_computecpums_nice_sum + monitor_computecpums_system_sum + monitor_computecpums_irq_sum + monitor_computecpums_softirq_sum)/(monitor_computecpums_user_sum + monitor_computecpums_nice_sum + monitor_computecpums_system_sum + monitor_computecpums_idle_sum + monitor_computecpums_iowait_sum + monitor_computecpums_irq_sum + monitor_computecpums_softirq_sum))) +
  scale_x_log10(breaks = log_breaks(n=10), label = scales::label_comma(accuracy = 0.1)) +
  scale_y_continuous(breaks = pretty_breaks(n=10), label = scales::label_comma(accuracy = 1)) +
  labs(title = "CPU load", color = "% NDP", shape = "% NDP") +
  xlab("Throughput [requests/second]") + ylab("Cpu usage (%)")

pdf(paste0(paper_plot_path, "cpu_load.pdf"), width=paper_plot_w, height=paper_plot_h, useDingbats = FALSE, family = paper_font, pointsize = paper_pointsize)
plot(gplt)
dev.off()
gplt
```

```{r plot_faasm_load}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_computefaasm_started_avg, group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_storagefaasm_started_avg, group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'identity', breaks = breaks_pretty(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = breaks_pretty(n=12)) +
  labs(title = "Average started faasm tasks") +
  xlab("Req/s") + ylab("count")
```

```{r plot_faasm_load2}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_computefaasm_waiting_queued_avg, group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_storagefaasm_waiting_queued_avg, group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'identity', breaks = breaks_pretty(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = breaks_pretty(n=12)) +
  labs(title = "Average queued-waiting faasm tasks") +
  xlab("Req/s") + ylab("count")
```

```{r plot_cpu_softirq}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_computecpums_softirq_sum / total_requests, group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_storagecpums_softirq_sum / total_requests, group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'identity', breaks = breaks_pretty(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = breaks_pretty(n=12)) +
  labs(title = "softirq ms") +
  xlab("Req/s") + ylab("count")
```

```{r plot_cpu_cswitches}
ggplot(t_data %>% filter(opts_req_rps>50)) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_computecswitches_sum / (opts_req_time), group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_storagecswitches_sum / (opts_req_time), group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'identity', breaks = breaks_pretty(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = breaks_pretty(n=12)) +
  labs(title = "Average context switches per second") +
  xlab("Req/s") + ylab("count/sec")
```

```{r plot_cpu_cswitches_req}
ggplot(t_data %>% filter(opts_req_rps>50)) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_computecswitches_sum / (total_requests), group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_storagecswitches_sum / (total_requests), group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity') +
  labs(title = "Average context switches per request") +
  xlab("Req/s") + ylab("count/request")
```

```{r plot_load_req}
ggplot(t_data %>% filter(opts_req_rps>30)) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_computeload_avg1_avg, group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_storageload_avg1_avg, group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity') +
  labs(title = "Load") +
  xlab("Req/s") + ylab("1m average load")
```

```{r plot_cpu_ms}
ggplot(t_data %>% filter(opts_req_rps>30)) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = (monitor_computecpums_user_sum + monitor_computecpums_system_sum + monitor_computecpums_nice_sum) / (results_count), group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = (monitor_storagecpums_user_sum + monitor_storagecpums_system_sum + monitor_storagecpums_nice_sum) / (results_count), group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity') +
  labs(title = "Average CPU ms per request (user+system)") +
  xlab("Req/s") + ylab("count")
```

```{r plot_cpu_idle_ms}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = (monitor_computecpums_idle_sum) / total_requests, group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = (monitor_storagecpums_idle_sum) / total_requests, group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Average CPU idle ms per request (user+system)") +
  xlab("Req/s") + ylab("ms")
```

```{r plot_mem_active_c}
cmembase <- as.double(min(t_data$monitor_computemem_active_min)) - 1.0
smembase <- as.double(min(t_data$monitor_storagemem_active_min)) - 1.0
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_computemem_active_avg / cmembase, group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = pretty_breaks(n=20)) +
  labs(title = "Average Active memory over baseline") +
  xlab("Req/s") + ylab("bytes")
```

```{r plot_mem_active_s}
cmembase <- min(t_data$monitor_computemem_active_min)
smembase <- min(t_data$monitor_storagemem_active_min)
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_storagemem_active_avg - smembase, group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = pretty_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Average Active memory per request over baseline") +
  xlab("Req/s") + ylab("bytes")
```

```{r plot_net_tx_bytes}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_computenet_tx_bytes_sum / total_requests, group = opts_ndp, color = interaction(opts_ndp), linetype = "Compute")) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = monitor_storagenet_tx_bytes_sum / total_requests, group = opts_ndp, color = interaction(opts_ndp), linetype = "Storage")) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Total bytes per request sent from node over network") +
  xlab("Req/s") + ylab("bytes/request")
```

```{r plot_net_tx_sum_bytes}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = (monitor_computenet_tx_bytes_sum + monitor_storagenet_tx_bytes_sum) / total_requests, group = opts_ndp, color = opts_ndp)) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1), expand = c(0.01, 0.01)) +
  scale_y_continuous(trans = 'identity', expand = c(0.1,0), limits = c(0, NA), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Total bytes per request sent over network") +
  xlab("Req/s") + ylab("bytes/request")
```

```{r plot_net_tx_sum_bytes_per_sec}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = opts_req_rps, y = (monitor_computenet_tx_bytes_sum + monitor_storagenet_tx_bytes_sum) / (opts_req_time), group = opts_ndp, color = opts_ndp)) +
  scale_x_continuous(trans = 'identity', breaks = pretty_breaks(n=20), label = scales::label_comma(accuracy = 1), expand = c(0.01, 0.01)) +
  scale_y_continuous(trans = 'identity', expand = c(0.1,0), limits = c(0, NA), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Total bytes per second sent over network") +
  xlab("Req/s") + ylab("bytes/second")
```

```{r plot_xverify_rps}
ggplot(t_data) +
  geom_point(stat = 'identity', aes(x = opts_req_rps, y = avg_rps_avg_rps, group = opts_ndp, color = opts_ndp, shape=opts_ndp)) +
  scale_x_continuous(trans = 'identity', label = scales::label_comma(accuracy = 1), expand = c(0.01, 0.01)) +
  scale_y_continuous(trans = 'identity', expand = c(0.1,0), limits = c(0, NA), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Xverify RPS/RPS") +
  ylab("Real Req/s") + xlab("Requested Req/s")
```

```{r plot_xverify_ndp}
ggplot(t_data) +
  geom_point(stat = 'identity', aes(x = opts_actual_ndp, y = opts_ndp, group = opts_ndp, color = opts_ndp)) +
  labs(title = "Xverify NDP") +
  xlab("Real NDP") + ylab("Requested NDP")
```
