---
title: "Faasm latency measurements - Frankenstein dataset"
author: "Jakub Szewczyk"
date: "15-09-2021"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(rio)
library(scales)
knitr::opts_chunk$set(echo = FALSE)
```

```{r read_csv, include=FALSE, cache=TRUE, cache.extra = file.info("table.csv")}
raw_csv <- import('table.csv')

t_data <- raw_csv %>%
  mutate (
    opts_host = factor(opts_host),
    opts_user = factor(opts_user),
    opts_function = factor(opts_function),
    opts_ndp = factor(opts_ndp),
    total_requests = avg_rps_avg_rps * opts_req_time,
  )

```

## Latencies

```{r plot_lat}
plot_scale <- 1.0/1000.0
ggplot(t_data,
    aes(x = avg_rps_avg_rps, ymin = latency_us_q1pct*plot_scale, ymax = latency_us_q99pct*plot_scale, lower = latency_us_q1*plot_scale, middle = latency_us_med*plot_scale, upper = latency_us_q3*plot_scale)) +
  geom_boxplot(stat = 'identity', aes(group = interaction(avg_rps_avg_rps, opts_function, opts_ndp), color = interaction(opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Latency for a given request per second rate") +
  xlab("Req/s") + ylab("milliseconds")
```

```{r plot_lat_zoom}
plot_scale <- 1.0/1000.0
ggplot(t_data %>% filter(avg_rps_avg_rps >= 250) %>% filter(avg_rps_avg_rps <= 600),
    aes(x = avg_rps_avg_rps, ymin = latency_us_q1pct*plot_scale, ymax = latency_us_q99pct*plot_scale, lower = latency_us_q1*plot_scale, middle = latency_us_med*plot_scale, upper = latency_us_q3*plot_scale)) +
  geom_boxplot(stat = 'identity', aes(group = interaction(avg_rps_avg_rps, opts_function, opts_ndp), color = interaction(opts_function, opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Latency for a given request per second rate") +
  xlab("Req/s") + ylab("milliseconds")
```

```{r plot_lat_smooth}
plot_scale <- 1.0/1000.0
ggplot(t_data,
    aes(x = opts_req_rps, ymin = latency_us_q1*plot_scale, y = latency_us_med*plot_scale, ymax = latency_us_q3*plot_scale)) +
  geom_smooth(stat = 'identity', aes(group = interaction(opts_function,opts_ndp), color = interaction(opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(y=errors_count, group = interaction(opts_function,opts_ndp), color = interaction(opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Latency for a given request per second rate") +
  xlab("Req/s") + ylab("milliseconds")
```

```{r plot_lat_smooth_zoom}
plot_scale <- 1.0/1000.0
ggplot(t_data %>% filter(avg_rps_avg_rps >= 200),
    aes(x = avg_rps_avg_rps, ymin = latency_us_q1*plot_scale, y = latency_us_med*plot_scale, ymax = latency_us_q3*plot_scale)) +
  geom_smooth(stat = 'identity', aes(group = interaction(opts_function,opts_ndp), color = interaction(opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(y=errors_count, group = interaction(opts_function,opts_ndp), color = interaction(opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Latency for a given request per second rate") +
  xlab("Req/s") + ylab("milliseconds")
```

```{r plot_cpu_load}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_computeprocs_running_avg, group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_storageprocs_running_avg, group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'identity', breaks = breaks_pretty(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = breaks_pretty(n=12)) +
  labs(title = "Average RUNNING threads") +
  xlab("Req/s") + ylab("count")
```

```{r plot_faasm_load}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_computefaasm_started_avg, group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_storagefaasm_started_avg, group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'identity', breaks = breaks_pretty(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = breaks_pretty(n=12)) +
  labs(title = "Average started faasm tasks") +
  xlab("Req/s") + ylab("count")
```

```{r plot_faasm_load2}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_computefaasm_waiting_queued_avg, group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_storagefaasm_waiting_queued_avg, group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'identity', breaks = breaks_pretty(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = breaks_pretty(n=12)) +
  labs(title = "Average queued-waiting faasm tasks") +
  xlab("Req/s") + ylab("count")
```

```{r plot_cpu_softirq}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_computecpums_softirq_sum / total_requests, group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_storagecpums_softirq_sum / total_requests, group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'identity', breaks = breaks_pretty(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = breaks_pretty(n=12)) +
  labs(title = "softirq ms") +
  xlab("Req/s") + ylab("count")
```

```{r plot_cpu_cswitches}
ggplot(t_data %>% filter(avg_rps_avg_rps>50)) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_computecswitches_sum / (opts_req_time), group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_storagecswitches_sum / (opts_req_time), group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'identity', breaks = breaks_pretty(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = breaks_pretty(n=12)) +
  labs(title = "Average context switches per second") +
  xlab("Req/s") + ylab("count/sec")
```

```{r plot_cpu_cswitches_req}
ggplot(t_data %>% filter(avg_rps_avg_rps>50)) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_computecswitches_sum / (total_requests), group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_storagecswitches_sum / (total_requests), group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity') +
  labs(title = "Average context switches per request") +
  xlab("Req/s") + ylab("count/request")
```

```{r plot_load_req}
ggplot(t_data %>% filter(avg_rps_avg_rps>150)) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_computeload_avg1_avg, group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_storageload_avg1_avg, group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity') +
  labs(title = "Load") +
  xlab("Req/s") + ylab("1m average load")
```

```{r plot_cpu_ms}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = (monitor_computecpums_user_sum + monitor_computecpums_system_sum + monitor_computecpums_nice_sum) / total_requests, group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = (monitor_storagecpums_user_sum + monitor_storagecpums_system_sum + monitor_storagecpums_nice_sum) / total_requests, group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity') +
  labs(title = "Average CPU ms per request (user+system)") +
  xlab("Req/s") + ylab("count")
```

```{r plot_cpu_idle_ms}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = (monitor_computecpums_idle_sum) / total_requests, group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = (monitor_storagecpums_idle_sum) / total_requests, group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Average CPU idle ms per request (user+system)") +
  xlab("Req/s") + ylab("ms")
```

```{r plot_mem_active}
cmembase <- min(t_data$monitor_computemem_active_min)
smembase <- min(t_data$monitor_storagemem_active_min)
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_computemem_active_avg - cmembase, group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_storagemem_active_avg - smembase, group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'identity', breaks = pretty_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Average Active memory per request over baseline") +
  xlab("Req/s") + ylab("bytes")
```

```{r plot_net_tx_bytes}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_computenet_tx_bytes_sum / total_requests, group = interaction(opts_function,opts_ndp), color = interaction('compute',opts_function,opts_ndp))) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = monitor_storagenet_tx_bytes_sum / total_requests, group = interaction(opts_function,opts_ndp), color = interaction('storage',opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  scale_y_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Total bytes per request sent from node over network") +
  xlab("Req/s") + ylab("bytes/request")
```

```{r plot_net_tx_sum_bytes}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = (monitor_computenet_tx_bytes_sum + monitor_storagenet_tx_bytes_sum) / total_requests, group = interaction(opts_function,opts_ndp), color = interaction(opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1), expand = c(0.01, 0.01)) +
  scale_y_continuous(trans = 'identity', expand = c(0.1,0), limits = c(0, NA), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Total bytes per request sent over network") +
  xlab("Req/s") + ylab("bytes/request")
```

```{r plot_net_tx_sum_bytes_per_sec}
ggplot(t_data) +
  geom_line(stat = 'identity', aes(x = avg_rps_avg_rps, y = (monitor_computenet_tx_bytes_sum + monitor_storagenet_tx_bytes_sum) / (opts_req_time), group = interaction(opts_function,opts_ndp), color = interaction(opts_function,opts_ndp))) +
  scale_x_continuous(trans = 'log', breaks = log_breaks(n=20), label = scales::label_comma(accuracy = 1), expand = c(0.01, 0.01)) +
  scale_y_continuous(trans = 'identity', expand = c(0.1,0), limits = c(0, NA), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Total bytes per second sent over network") +
  xlab("Req/s") + ylab("bytes/second")
```

```{r plot_xverify_rps}
ggplot(t_data) +
  geom_point(stat = 'identity', aes(x = avg_rps_avg_rps, y = opts_req_rps, group = interaction(opts_function,opts_ndp), color = interaction(opts_function,opts_ndp), shape=opts_ndp)) +
  scale_x_continuous(trans = 'identity', label = scales::label_comma(accuracy = 1), expand = c(0.01, 0.01)) +
  scale_y_continuous(trans = 'identity', expand = c(0.1,0), limits = c(0, NA), label = scales::label_comma(accuracy = 1)) +
  labs(title = "Xverify RPS/RPS") +
  xlab("Real Req/s") + ylab("Requested Req/s")
```

```{r plot_xverify_ndp}
ggplot(t_data) +
  geom_point(stat = 'identity', aes(x = opts_actual_ndp, y = opts_ndp, group = interaction(opts_function,opts_ndp), color = interaction(opts_function,opts_ndp))) +
  labs(title = "Xverify NDP") +
  xlab("Real NDP") + ylab("Requested NDP")
```
