[package]
name = "analyse-results"
version = "0.1.0"
authors = ["Jakub Szewczyk <git@kubasz.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
